name: Deploy Package
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-?**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Deploy to gh package registry
        run: ./mvnw --batch-mode deploy 
        env:
          GITHUB_TOKEN: ${{ github.token }}
